locale = "en"
label = "English"
weight = 1
title = "Bruce loves to cook"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Bruce loves to cook, our family cookbook."
